---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: phpmyadmin-basic-auth
  namespace: wordpress
spec:
  encryptedData:
    auth: AgBt/4Gg+uQm4ADYZyymh4wMhD8+hWAwIgF3BQ6Nw7vCWMV3SbVb/kAgU4ovOtBcL/WS6UaJalmvvv9b9A8l/pyxzpbdVywjSa1u13noJEjTV3OiWsxg7+0YdQSBuUKTiYPZl9mGeUJluvuwpfxOggmyd/Aw2CfCwX/oziJ7B1/g6FECoDdHazW8IMDtItYJL5kP5NAp8MJZJjrNTJtaEvkCig869MlGdHtjSxspZ+X4PtLBid2fpRnEZnV2ei7v2CvgoHZcZCc85kYK+IapWGMHS3ZLynDXUh4E/llhIgOwlSeM3FaDM0bymDXcXTlOJo4alxoa35dLnj8NEJqMyKKrCV7zQoc+F5aPV7heW7DfJUWBLsGQ3oADQJ8QFwjhAROPG50t6wCSFA/VNNSVCCGalelHXeYz6XChRYctd37l1UJQ8kFpOi1Ej4fgPQDqA/Cc7OnVd+aNf9qevdCfe3YZ2ZrW+DzrR6U5YcT0r6U450fcGosPsAIJ+I7wL3Ax8h/hbkRsmrqNsivZBvbPcKGjkm2tm+od1H89B2HsdQUsjDFbbT8RRV8uJCZaEC1kRy3Oi8N1At1ORyYlIlZLDFXW/t2LJ9Rlw+RGRxVc4Iv+n2mxJITfoYAMOkRhes9HkIUt437wuEWplp8EfOnCEAxKIw03mJk//ZaVvFvfcAielfbaZ5qB4xOKYvsWola4fLRRSb4qWHLnUQh1uDfypdn6PVT7dbG8nHkz1yBRCW1BAXh3IMJYjC1P6vb9quMFHdjeZja5tjk=
  template:
    metadata:
      name: phpmyadmin-basic-auth
      namespace: wordpress
