apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin:5.2.1
        env:
        - name: PMA_HOST
          value: mysql.wordpress.svc.cluster.local
        - name: PMA_PORT
          value: "3306"
        - name: PMA_USER
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: mysql-user
        - name: PMA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: mysql-password
        - name: UPLOAD_LIMIT
          value: "4096M"
        - name: MEMORY_LIMIT
          value: "1024M"
        - name: MAX_EXECUTION_TIME
          value: "0"
        ports:
        - containerPort: 80
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: wordpress
spec:
  selector:
    app: phpmyadmin
  ports:
  - port: 80
    targetPort: http
